### ISSUE TITLE
Write basic partitioning functionality.

### ISSUE THREAD

**Issue by Peder2911** [prio-data/views_partitioning#1]
We should plan the format of this package in terms of what it should do, and what the API should look like.

**Comment by Peder2911** [comment]
I've written a fully functional, simple API for partitioning data. It is invoked like this:
```
from views_partitioning.data_partitioner import DataPartitioner
partitioner = DataPartitioner(...)
partitioned_data = partitioner(PARTITION_NAME, TIME_PERIOD_NAME, data)
```
For instance, using the legacy partitioning scheme:
```
a_train_data = partitioner("A","train",data)
```
 The code is compatible with legacy-style Period objects:
```
from views_partitioning.data_partitioner import DataPartitioner
from views_partitioning import legacy
partitioner = DataPartitioner.from_legacy(legacy.Period(...))
```

Have a look before considering this done @hhegre ,@jimdale ?

**Comment by hhegre** [comment]
We will need also to use partitioning by unit in addition to by time, something which ViEWS2 does not support easily. We might at some point move to estimating ensemble weights by units instead of by period, even.  Would this be controlled from here?

**Comment by Peder2911** [comment]
It could, but it might be reasonable to just use `df.loc[:, COUNTRIES]`. The reason for wrapping the time-partitioning functionality seen here is just to be able to name time-periods, and at some point store / define them centrally. Would it be useful to store the lists of units to subset in the same way? If not, then subsetting by unit is well enough supported in pandas, and doesn't need to be wrapped.

**Comment by hhegre** [comment]
I agree to this. Only reason would be to collect this in the same place, to facilitate the generation of metadata. But most important is that it should be possible to only have train/test partition, not train/calibration/test, and do calibration etc using CV in the train partition, if we decide to do so.

**Comment by hhegre** [comment]
Useful to store the lists of units: Not necessarily, but it should be possible to replicate this easily, i.e. a random draw of countries should be replicable.

**Comment by Peder2911** [comment]
Good good! Random draws can be made replicable by setting the seed in `random.Random` when picking the countries.

**Comment by Peder2911** [comment]
With this partitioning functionality, you can do any kind of partitioning. Train / calib / test / predict. It's just a nested dictionary where partitioning periods are defined like this (for example):
```
{
   "a":
   {
      "train":(1,10),
      "test":(11,20),
   },
   "b":
   {
      "train":(1,20),
      "test":(21,30),
   }
}
```

**Comment by Peder2911** [comment]
This dict. is wrapped in an object which lets you apply the partitions to data, yielding partitioned data according to the values in the dictionary. In addition, you can instantiate the object with `DataPartitioner.from_legacy_periods(...)` where you pass a list of `Period` objects, which are familiar to you.

**Comment by mihaicroicu** [comment]
But does it work for multi-dimensional partitioning? e.g. A is set of countries {1,2,…92} at time periods {1–9}, B is set of countries… etc. etc.?

And if not, does it allow for partitioning on other dimensions but time / first index?

Best,
Mihai

> On 17 Sep 2021, at 12:48, Peder G. Landsverk ***@***.***> wrote:
>
> This dict. is wrapped in an object which lets you apply the partitions to data, yielding partitioned data according to the values in the dictionary. In addition, you can instantiate the object with DataPartitioner.from_legacy_periods(...) where you pass a list of Period objects, which are familiar to you.
>
>









När du har kontakt med oss på Uppsala universitet med e-post så innebär det att vi behandlar dina personuppgifter. För att läsa mer om hur vi gör det kan du läsa här: http://www.uu.se/om-uu/dataskydd-personuppgifter/

E-mailing Uppsala University means that we will process your personal data. For more information on how this is performed, please read here: http://www.uu.se/en/about-uu/data-protection-policy

**Comment by Peder2911** [comment]
No, this is just for simple time-partitioning using periodizations.

Partitioning is a really simple process, it's just indexing. The only reason for wrapping this, like I have done here, is for coordination (i.e centrally storing time-periods to make sure everyone is training / predicting for the same periods). I won't wrap other kinds of partitioning unless there's a good reason for it?

**Comment by Peder2911** [comment]
Considering this done.
